import { mockAdminUsers, mockConversations, mockRoomSeats } from "../state/mockState";

const appChrome = (title: string, active: string): string => `<header class="navbar route-navbar"><a class="logo" href="#top"><span class="logo-mark">S</span><span>ses<span>on</span></span></a><nav><a class="${active === "discover" ? "active" : ""}" href="#top">Keşfet</a><a class="${active === "room" ? "active" : ""}" href="/room">Canlı odalar</a><a href="/profile">Profil</a><a href="/messages">Mesajlar</a><a href="/nova">Nova</a><a href="/lina">Lina</a></nav><div class="nav-right"><span class="live-status"><i></i> 2.4K kişi online</span><a class="login" href="/auth">Giriş yap</a><a class="join" href="/auth">Kayıt ol <span>↗</span></a><button class="hamburger" aria-label="Menü">☰</button></div></header><div class="route-title"><a href="#top">← Ana sayfa</a><span>${title}</span></div>`;

export function authView(): string {
  return `<div class="route-page auth-page"><div class="auth-backdrop-glow"></div>${appChrome("Giriş / Kayıt", "") }<main class="auth-layout"><section class="auth-pitch"><span class="eyebrow"><i></i> SESON'A HOŞ GELDİN</span><h1>Sesinle<br /><em>yerini bul.</em></h1><p>Binlerce sohbete katıl, kendi hikâyeni anlat. SesOn'da herkesin söyleyecek bir şeyi var.</p><div class="auth-pitch-wave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><small>10.000+ kişi şu an içeride</small></section><section class="auth-screen"><div class="auth-screen-head"><span class="auth-dot"></span><span>GÜVENLİ GİRİŞ</span><b>⌁</b></div><div class="auth-screen-tabs"><button class="active" data-auth-tab="login">Giriş yap</button><button data-auth-tab="signup">Kayıt ol</button></div><h2 data-auth-heading>Tekrar <em>hoş geldin.</em></h2><p data-auth-copy>SesOn'a devam etmek için e-posta adresini gir.</p><form class="auth-form"><label for="route-email">E-posta adresin</label><input id="route-email" type="email" placeholder="ornek@email.com" required /><label for="route-password">Şifren</label><input id="route-password" type="password" placeholder="••••••••" required /><button class="join" type="submit" data-auth-submit>Giriş yap <span>→</span></button></form><div class="auth-divider"><span>veya</span></div><button class="social-button" type="button"><strong>G</strong> Google ile devam et</button><small class="auth-legal">Devam ederek Kullanım Koşulları ve Gizlilik Politikası'nı kabul etmiş olursun.</small></section></main></div>`;
}

export function roomView(): string {
  const seats = mockRoomSeats;
  const seatMarkup = seats.map((seat, index) => `<button class="seat ${seat ? "occupied" : "empty"}" type="button" aria-label="${seat ? `${seat} konuşmacı koltuğu` : `Boş konuşmacı koltuğu ${index + 1}`}">${seat || "+"}<small>${seat ? "konuşuyor" : "boş"}</small></button>`).join("");
  return `<div class="route-page room-page">${appChrome("Canlı oda", "room")}<main class="room-layout"><section class="room-stage"><div class="room-stage-top"><div><span class="eyebrow"><i></i> CANLI SES ODASI</span><h1>Geceye Bir Şarkı</h1><p>Mert & Ece · Müzik ve sohbet</p></div><span class="room-live-count">◉ 1.2K dinliyor</span></div><div class="room-visual"><div class="room-glow"></div><div class="room-wave wave-a"></div><div class="room-wave wave-b"></div><div class="room-host-avatar">ME</div><span class="room-host-ring"></span><span class="room-note">♫</span></div><div class="speaker-row"><span><b>ME</b><small>Mert · host</small></span><span><b>EC</b><small>Ece · co-host</small></span><span><b>LD</b><small>Lara</small></span></div><div class="room-chat-preview"><span class="chat-avatar">SY</span><p><b>Selin</b> Çok güzel bir şarkı oldu ✨</p><span>♡</span></div></section><aside class="seat-panel"><div class="seat-panel-head"><div><span class="eyebrow">KONUŞMACI KOLTUĞU</span><h2>Odaya katıl</h2></div><button class="round">⋯</button></div><p>Boş bir koltuğa dokunarak sohbete katılabilirsin.</p><div class="seat-grid">${seatMarkup}</div><div class="room-actions"><button class="join" type="button" data-raise-hand>✋ El kaldır</button><button class="room-action" type="button" data-mic-toggle aria-pressed="false">♫</button><button class="room-action" type="button">♡</button></div></aside></main><section class="room-footer-bar"><span><b>Geceye Bir Şarkı</b><small>Oda herkese açık · 2 moderatör</small></span><button class="leave-button" type="button">Odadan ayrıl</button></section></div>`;
}

export function profileView(): string {
  return `<div class="route-page profile-page">${appChrome("Profil", "profile")}<main class="profile-layout"><section class="profile-hero-card"><div class="profile-cover"><span class="profile-orbit"></span><span class="profile-big-avatar">LD</span></div><div class="profile-main"><div><h1>Lara Deniz <span class="verified">✦</span></h1><p>@laradeniz · İstanbul</p><span class="profile-badge">✦ ARİSTOKRAT SEVİYE 8</span></div><div class="profile-actions"><button class="outline" type="button" data-profile-edit>Düzenle</button><button class="join" type="button" data-follow>Takip et <span>＋</span></button></div></div><div class="profile-stats"><span><b>24.8K</b><small>Takipçi</small></span><span><b>318</b><small>Takip</small></span><span><b>1.4K</b><small>Paylaşılan dk</small></span><span><b>89</b><small>Oda</small></span></div></section><section class="profile-columns"><div class="profile-content"><div class="profile-tabs"><button class="active">Paylaşımlar</button><button>Oda geçmişi</button><button>Rozetler</button></div><article class="profile-post"><div class="post-head"><span class="person-avatar pink">LD</span><span><b>Lara Deniz</b><small>2 saat önce · Herkese açık</small></span><button>⋯</button></div><p>Bu gece sesini dinleyen herkese teşekkürler. Bazen tek ihtiyacımız olan, gerçekten dinlenmek. ✨</p><div class="post-wave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><span>02:48</span></div><div class="post-actions"><span>♡ 248</span><span>◌ 31</span><span>↗ Paylaş</span></div></article></div><aside class="profile-side"><div class="side-panel"><span class="eyebrow">KAZANIMLAR</span><h2>SesCoin cüzdanı</h2><strong class="coin-balance">12,480 <small>SC</small></strong><p>Bu hafta +1,240 SesCoin kazandın.</p><button class="outline" type="button" data-wallet>Cüzdanı görüntüle →</button></div><div class="side-panel mini-badges"><span class="eyebrow">ROZETLER</span><div><i>♛</i><i>✦</i><i>◈</i><i>♫</i></div></div></aside></section></main></div>`;
}

export function messagesView(): string {
  const list = mockConversations.map((item, i) => `<button class="conversation ${i === 0 ? "active" : ""}" data-conversation="${item.id}" type="button"><span class="person-avatar ${item.tone}">${item.initials}</span><span><b>${item.name}</b><small>${item.preview}</small></span><time>${i === 0 ? "2 dk" : i === 1 ? "18 dk" : "1 sa"}</time></button>`).join("");
  return `<div class="route-page messages-page">${appChrome("Mesajlar", "messages")}<main class="messages-layout"><aside class="conversation-panel"><div class="messages-head"><div><span class="eyebrow">TOPLULUK</span><h1>Mesajlar</h1></div><button class="round">＋</button></div><label class="search-box">⌕ <input placeholder="Mesajlarda ara" /></label><div class="conversation-list">${list}</div></aside><section class="thread-panel"><div class="thread-head"><span class="person-avatar violet">ES</span><div><b>Ece Su</b><small>Şu an aktif · @ecesu</small></div><button class="round">⋯</button></div><div class="thread-body"><div class="thread-date">BUGÜN</div><div class="message received">Selam Lara! Bu akşamki oda için hazır mısın? <small>20:41</small></div><div class="message sent">Hazırım! Yeni şarkı listesini de hazırladım ✨ <small>20:42</small></div><div class="message received">Harika, o zaman birazdan görüşürüz. <small>20:43</small></div></div><form class="message-composer" data-message-form><button type="button">＋</button><input placeholder="Bir mesaj yaz..." /><button class="send-button" type="submit">↑</button></form></section></main></div>`;
}

export function aiView(kind: "nova" | "lina"): string {
  const nova = kind === "nova";
  return `<div class="route-page ai-page ${nova ? "nova-page" : "lina-page"}">${appChrome(nova ? "Nova AI" : "Lina AI", "") }<main class="ai-layout"><section class="ai-intro"><div class="ai-orb ${nova ? "nova-orb" : "lina-orb"}"><span>${nova ? "N" : "L"}</span></div><span class="eyebrow"><i></i> ${nova ? "NOVA AI · SES ANALİZİ" : "LINA AI · TOPLULUK ASİSTANI"}</span><h1>${nova ? "Sesini daha iyi tanı." : "Her sohbette yanında."}</h1><p>${nova ? "Nova, ses tonunu ve içeriklerini anlayarak sana daha güçlü bir ifade alanı açar." : "Lina, SesOn topluluğunda keşfetmene, konuşmana ve bağlantı kurmana yardımcı olur."}</p><div class="ai-suggestions"><button>${nova ? "Ses profilimi analiz et" : "Bana bir oda öner"} <span>→</span></button><button>${nova ? "İçerik fikri üret" : "Bugün ne konuşuluyor?"} <span>→</span></button><button>${nova ? "Sonuçlarımı göster" : "Yeni insanlarla tanış"} <span>→</span></button></div></section><section class="ai-chat"><div class="ai-chat-head"><span class="ai-mini-orb ${nova ? "nova-orb" : "lina-orb"}">${nova ? "N" : "L"}</span><span><b>${nova ? "Nova AI" : "Lina AI"}</b><small>${nova ? "Ses koçun" : "Topluluk asistanın"}</small></span><i></i></div><div class="ai-messages"><div class="ai-bubble">${nova ? "Merhaba Lara. Bugün sesindeki enerjiyi keşfetmeye hazır mısın?" : "Merhaba! Bugün sana nasıl yardımcı olabilirim?"}</div><div class="ai-bubble user">${nova ? "Evet, son kaydımı analiz eder misin?" : "Bana ilgi alanlarıma göre bir oda öner."}</div><div class="ai-bubble">${nova ? "Elbette. Sesin sıcak ve dengeli geliyor. Vurgularını biraz daha öne çıkarabiliriz." : "Müzik ve gece sohbetleri ilgini çekebilir. Geceye Bir Şarkı odası şu an canlı."}</div></div><form class="ai-composer"><input placeholder="${nova ? "Nova'ya bir şey sor..." : "Lina'ya yaz..."}" /><button class="send-button" type="submit">↑</button></form></section></main></div>`;
}

export function adminView(): string {
  const rows = mockAdminUsers;
  const rowMarkup = rows.map((row) => `<tr><td><span class="table-avatar ${row.tone}"></span><b>${row.name}</b></td><td>${row.type}</td><td><span class="status-pill ${row.status === "Aktif" ? "ok" : "pending"}">${row.status}</span></td><td><button class="table-action" data-admin-action type="button">⋯</button></td></tr>`).join("");
  return `<div class="route-page admin-page"><header class="admin-top"><a class="logo" href="#top"><span class="logo-mark">S</span><span>ses<span>on</span></span></a><span class="admin-label">OPERATIONS CONSOLE</span><a href="#top" class="admin-back">Ana sayfa ↗</a></header><main class="admin-layout"><aside class="admin-sidebar"><span class="eyebrow">YÖNETİM</span><a class="active" href="/admin">Genel bakış</a><a href="/admin">Kullanıcılar <b>12</b></a><a href="/admin">Canlı odalar</a><a href="/admin">Raporlar</a><a href="/admin">SesCoin</a><a href="/admin">Ayarlar</a><div class="admin-health"><i></i><span>Sistemler çalışıyor<small>Son kontrol: şimdi</small></span></div></aside><section class="admin-content"><div class="admin-heading"><div><span class="eyebrow">15 AĞUSTOS 2026</span><h1>İyi akşamlar, ekip.</h1></div><button class="join">Rapor oluştur <span>＋</span></button></div><div class="admin-kpis"><article><small>AKTİF KULLANICI</small><b>24,892</b><span>↑ 8.4% bu hafta</span></article><article><small>CANLI ODALAR</small><b>1,208</b><span>↑ 12.1% bu hafta</span></article><article><small>BEKLEYEN RAPOR</small><b>38</b><span class="warning">İnceleme gerekli</span></article><article><small>SESCOIN HACMİ</small><b>₺84.2K</b><span>↑ 18.6% bu ay</span></article></div><div class="admin-grid"><section class="admin-table-panel"><div class="admin-panel-head"><label class="admin-search">⌕ <input data-admin-search placeholder="Kullanıcı veya içerik ara" /></label><div><span class="eyebrow">SON AKTİVİTELER</span><h2>Kontrol merkezi</h2></div><button class="outline">Tümünü gör →</button></div><table><thead><tr><th>İSİM</th><th>TÜR</th><th>DURUM</th><th></th></tr></thead><tbody>${rowMarkup}</tbody></table><div class="empty-state" data-admin-empty hidden>Aramanla eşleşen kayıt bulunamadı.</div></section><section class="admin-chart"><span class="eyebrow">GÜNLÜK AKTİFLİK</span><h2>Topluluk ritmi</h2><div class="chart-bars"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="chart-labels"><span>Pzt</span><span>Sal</span><span>Çar</span><span>Per</span><span>Cum</span><span>Cmt</span><span>Paz</span></div></section></div></section></main></div>`;
}
